spring:
  application:
    name: todo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:employee-db
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

axon:
  axonserver:
    servers: localhost