spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: machine
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
